### ISSUE TITLE
Propose a structure of files to have an API built with FastAPI and test files.

### ISSUE THREAD

**Issue by achab** [Amenokal-Labs/legal-ai-assistant#11]
We want to create an API using FastAPI and have tests in the same project. We need to think about the structure of the repo.

The output of this task is to propose a file structure by answering in this issue. Once @romaissaMe and @Imad-Allal agree, we create a PR to move files to the right place.

**Comment by romaissaMe** [comment]
project/
├── app/
│   ├── api/
│   │   ├── routers/
│   │   │   ├── init.py
│   │   │   └── ask.py
│   │   │   └── ...
│    │  │── models/
│    │  │   ├── init.py
│   │   │   └── ...
│   │   └── init.py
│   ├── utils/
│   │   ├── init.py
│   │   ├──utils.py
│   │   └──anonymize.py
│   │   └──...
│   ├── main.py
│   └── config.py
├── tests/
│   ├── anonymize_test.py
│   └── ...
├── requirements.txt
└── README.md

@achab
